# Generated by Django 4.2.4 on 2023-08-04 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountDetails",
            fields=[
                (
                    "AccountNumber",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=1048)),
                ("email", models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UID",
            fields=[
                ("userID", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "AccountNumber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mybank.accountdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "ReferenceNum",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("senderBalance", models.IntegerField()),
                ("recieverBalance", models.IntegerField()),
                (
                    "reciever",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_reciever",
                        to="mybank.accountdetails",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_sender",
                        to="mybank.accountdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mybank.uid"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.IntegerField()),
                (
                    "AccountNumber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mybank.accountdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Authentication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mybank.uid"
                    ),
                ),
            ],
        ),
    ]
