# Generated by Django 4.2.4 on 2023-08-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mybank", "0002_authenticatetransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transactionAmount",
            field=models.IntegerField(default=0),
        ),
    ]
